CREATE TABLE IF NOT EXISTS person (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS expense (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    applied_at DATE NOT NULL,
    person_id SERIAL REFERENCES person (id) ON DELETE CASCADE,
    category_id SERIAL REFERENCES category (id) ON DELETE CASCADE
);